<?php

// This is a autogenerated file:ApifoxSchema

class ApifoxSchema {
    private ?string $file; // json:file Optional
    private ?string $fileHash; // json:fileHash Optional
    private ?string $fileID; // json:fileId Optional
    private string $fileName; // json:fileName Required
    private ?string $fileURL; // json:fileUrl Optional
    private ?string $notifyURL; // json:notifyUrl Optional
    private ?string $transferType; // json:transferType Optional

    /**
     * @param string|null $file
     * @param string|null $fileHash
     * @param string|null $fileID
     * @param string $fileName
     * @param string|null $fileURL
     * @param string|null $notifyURL
     * @param string|null $transferType
     */
    public function __construct(?string $file, ?string $fileHash, ?string $fileID, string $fileName, ?string $fileURL, ?string $notifyURL, ?string $transferType) {
        $this->file = $file;
        $this->fileHash = $fileHash;
        $this->fileID = $fileID;
        $this->fileName = $fileName;
        $this->fileURL = $fileURL;
        $this->notifyURL = $notifyURL;
        $this->transferType = $transferType;
    }

    /**
     * 文件流，最大200M。文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromFile(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 文件流，最大200M。文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @throws Exception
     * @return ?string
     */
    public function toFile(): ?string {
        if (ApifoxSchema::validateFile($this->file))  {
            if (!is_null($this->file)) {
                return $this->file; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::file');
    }

    /**
     * 文件流，最大200M。文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateFile(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::file");
            }
        }
        return true;
    }

    /**
     * 文件流，最大200M。文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @throws Exception
     * @return ?string
     */
    public function getFile(): ?string {
        if (ApifoxSchema::validateFile($this->file))  {
            return $this->file;
        }
        throw new Exception('never get to getFile ApifoxSchema::file');
    }

    /**
     * 文件流，最大200M。文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @return ?string
     */
    public static function sampleFile(): ?string {
        return 'ApifoxSchema::file::31'; /*31:file*/
    }

    /**
     * 文件的摘要哈希值，当上传了摘要值时，文件上传完之后，需要先做完整性比对，若比对不上，则报错提示“文件摘要值与实际文件不匹配”
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromFileHash(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 文件的摘要哈希值，当上传了摘要值时，文件上传完之后，需要先做完整性比对，若比对不上，则报错提示“文件摘要值与实际文件不匹配”
     *
     * @throws Exception
     * @return ?string
     */
    public function toFileHash(): ?string {
        if (ApifoxSchema::validateFileHash($this->fileHash))  {
            if (!is_null($this->fileHash)) {
                return $this->fileHash; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::fileHash');
    }

    /**
     * 文件的摘要哈希值，当上传了摘要值时，文件上传完之后，需要先做完整性比对，若比对不上，则报错提示“文件摘要值与实际文件不匹配”
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateFileHash(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::fileHash");
            }
        }
        return true;
    }

    /**
     * 文件的摘要哈希值，当上传了摘要值时，文件上传完之后，需要先做完整性比对，若比对不上，则报错提示“文件摘要值与实际文件不匹配”
     *
     * @throws Exception
     * @return ?string
     */
    public function getFileHash(): ?string {
        if (ApifoxSchema::validateFileHash($this->fileHash))  {
            return $this->fileHash;
        }
        throw new Exception('never get to getFileHash ApifoxSchema::fileHash');
    }

    /**
     * 文件的摘要哈希值，当上传了摘要值时，文件上传完之后，需要先做完整性比对，若比对不上，则报错提示“文件摘要值与实际文件不匹配”
     *
     * @return ?string
     */
    public static function sampleFileHash(): ?string {
        return 'ApifoxSchema::fileHash::32'; /*32:fileHash*/
    }

    /**
     * 文件ID，文件在本地电子签系统的唯一识别标识。不传值时，则系统将生成默认文件ID。传值时，则以传入的文件ID为准，最大长度64位,字符范围为[a-zA-Z0-9]；若文件ID已存在，则文件ID不变，更新文件（旧文件将被覆盖）。
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromFileID(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 文件ID，文件在本地电子签系统的唯一识别标识。不传值时，则系统将生成默认文件ID。传值时，则以传入的文件ID为准，最大长度64位,字符范围为[a-zA-Z0-9]；若文件ID已存在，则文件ID不变，更新文件（旧文件将被覆盖）。
     *
     * @throws Exception
     * @return ?string
     */
    public function toFileID(): ?string {
        if (ApifoxSchema::validateFileID($this->fileID))  {
            if (!is_null($this->fileID)) {
                return $this->fileID; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::fileID');
    }

    /**
     * 文件ID，文件在本地电子签系统的唯一识别标识。不传值时，则系统将生成默认文件ID。传值时，则以传入的文件ID为准，最大长度64位,字符范围为[a-zA-Z0-9]；若文件ID已存在，则文件ID不变，更新文件（旧文件将被覆盖）。
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateFileID(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::fileID");
            }
        }
        return true;
    }

    /**
     * 文件ID，文件在本地电子签系统的唯一识别标识。不传值时，则系统将生成默认文件ID。传值时，则以传入的文件ID为准，最大长度64位,字符范围为[a-zA-Z0-9]；若文件ID已存在，则文件ID不变，更新文件（旧文件将被覆盖）。
     *
     * @throws Exception
     * @return ?string
     */
    public function getFileID(): ?string {
        if (ApifoxSchema::validateFileID($this->fileID))  {
            return $this->fileID;
        }
        throw new Exception('never get to getFileID ApifoxSchema::fileID');
    }

    /**
     * 文件ID，文件在本地电子签系统的唯一识别标识。不传值时，则系统将生成默认文件ID。传值时，则以传入的文件ID为准，最大长度64位,字符范围为[a-zA-Z0-9]；若文件ID已存在，则文件ID不变，更新文件（旧文件将被覆盖）。
     *
     * @return ?string
     */
    public static function sampleFileID(): ?string {
        return 'ApifoxSchema::fileID::33'; /*33:fileID*/
    }

    /**
     * 文件完整名称（需带上文件后缀），长度最大255个字符。
     *
     * @param string $value
     * @throws Exception
     * @return string
     */
    public static function fromFileName(string $value): string {
        return $value; /*string*/
    }

    /**
     * 文件完整名称（需带上文件后缀），长度最大255个字符。
     *
     * @throws Exception
     * @return string
     */
    public function toFileName(): string {
        if (ApifoxSchema::validateFileName($this->fileName))  {
            return $this->fileName; /*string*/
        }
        throw new Exception('never get to this ApifoxSchema::fileName');
    }

    /**
     * 文件完整名称（需带上文件后缀），长度最大255个字符。
     *
     * @param string
     * @return bool
     * @throws Exception
     */
    public static function validateFileName(string $value): bool {
        if (!is_string($value)) {
            throw new Exception("Attribute Error:ApifoxSchema::fileName");
        }
        return true;
    }

    /**
     * 文件完整名称（需带上文件后缀），长度最大255个字符。
     *
     * @throws Exception
     * @return string
     */
    public function getFileName(): string {
        if (ApifoxSchema::validateFileName($this->fileName))  {
            return $this->fileName;
        }
        throw new Exception('never get to getFileName ApifoxSchema::fileName');
    }

    /**
     * 文件完整名称（需带上文件后缀），长度最大255个字符。
     *
     * @return string
     */
    public static function sampleFileName(): string {
        return 'ApifoxSchema::fileName::34'; /*34:fileName*/
    }

    /**
     * 文件获取链接地址，文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromFileURL(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 文件获取链接地址，文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @throws Exception
     * @return ?string
     */
    public function toFileURL(): ?string {
        if (ApifoxSchema::validateFileURL($this->fileURL))  {
            if (!is_null($this->fileURL)) {
                return $this->fileURL; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::fileURL');
    }

    /**
     * 文件获取链接地址，文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateFileURL(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::fileURL");
            }
        }
        return true;
    }

    /**
     * 文件获取链接地址，文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @throws Exception
     * @return ?string
     */
    public function getFileURL(): ?string {
        if (ApifoxSchema::validateFileURL($this->fileURL))  {
            return $this->fileURL;
        }
        throw new Exception('never get to getFileURL ApifoxSchema::fileURL');
    }

    /**
     * 文件获取链接地址，文件流与Url的方式二选一，不允许同时选择；传文档文件，则按照文件流的方式创建文件并返回文件id；选择文件路径，则从Url中下载文件后创建文件并返回文件id
     *
     * @return ?string
     */
    public static function sampleFileURL(): ?string {
        return 'ApifoxSchema::fileURL::35'; /*35:fileURL*/
    }

    /**
     * 异步回调地址，长度最大200个字符。文档上传成功后产生回调，基于返回的fileId识别回调。
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromNotifyURL(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 异步回调地址，长度最大200个字符。文档上传成功后产生回调，基于返回的fileId识别回调。
     *
     * @throws Exception
     * @return ?string
     */
    public function toNotifyURL(): ?string {
        if (ApifoxSchema::validateNotifyURL($this->notifyURL))  {
            if (!is_null($this->notifyURL)) {
                return $this->notifyURL; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::notifyURL');
    }

    /**
     * 异步回调地址，长度最大200个字符。文档上传成功后产生回调，基于返回的fileId识别回调。
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateNotifyURL(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::notifyURL");
            }
        }
        return true;
    }

    /**
     * 异步回调地址，长度最大200个字符。文档上传成功后产生回调，基于返回的fileId识别回调。
     *
     * @throws Exception
     * @return ?string
     */
    public function getNotifyURL(): ?string {
        if (ApifoxSchema::validateNotifyURL($this->notifyURL))  {
            return $this->notifyURL;
        }
        throw new Exception('never get to getNotifyURL ApifoxSchema::notifyURL');
    }

    /**
     * 异步回调地址，长度最大200个字符。文档上传成功后产生回调，基于返回的fileId识别回调。
     *
     * @return ?string
     */
    public static function sampleNotifyURL(): ?string {
        return 'ApifoxSchema::notifyURL::36'; /*36:notifyURL*/
    }

    /**
     * 转换类型：pdf（默认）、ofd
     *
     * @param ?string $value
     * @throws Exception
     * @return ?string
     */
    public static function fromTransferType(?string $value): ?string {
        if (!is_null($value)) {
            return $value; /*string*/
        } else {
            return null;
        }
    }

    /**
     * 转换类型：pdf（默认）、ofd
     *
     * @throws Exception
     * @return ?string
     */
    public function toTransferType(): ?string {
        if (ApifoxSchema::validateTransferType($this->transferType))  {
            if (!is_null($this->transferType)) {
                return $this->transferType; /*string*/
            } else {
                return  null;
            }
        }
        throw new Exception('never get to this ApifoxSchema::transferType');
    }

    /**
     * 转换类型：pdf（默认）、ofd
     *
     * @param string|null
     * @return bool
     * @throws Exception
     */
    public static function validateTransferType(?string $value): bool {
        if (!is_null($value)) {
            if (!is_string($value)) {
                throw new Exception("Attribute Error:ApifoxSchema::transferType");
            }
        }
        return true;
    }

    /**
     * 转换类型：pdf（默认）、ofd
     *
     * @throws Exception
     * @return ?string
     */
    public function getTransferType(): ?string {
        if (ApifoxSchema::validateTransferType($this->transferType))  {
            return $this->transferType;
        }
        throw new Exception('never get to getTransferType ApifoxSchema::transferType');
    }

    /**
     * 转换类型：pdf（默认）、ofd
     *
     * @return ?string
     */
    public static function sampleTransferType(): ?string {
        return 'ApifoxSchema::transferType::37'; /*37:transferType*/
    }

    /**
     * @throws Exception
     * @return bool
     */
    public function validate(): bool {
        return ApifoxSchema::validateFile($this->file)
            || ApifoxSchema::validateFileHash($this->fileHash)
            || ApifoxSchema::validateFileID($this->fileID)
            || ApifoxSchema::validateFileName($this->fileName)
            || ApifoxSchema::validateFileURL($this->fileURL)
            || ApifoxSchema::validateNotifyURL($this->notifyURL)
            || ApifoxSchema::validateTransferType($this->transferType);
    }

    /**
     * @return stdClass
     * @throws Exception
     */
    public function to(): stdClass  {
        $out = new stdClass();
        $out->{'file'} = $this->toFile();
        $out->{'fileHash'} = $this->toFileHash();
        $out->{'fileId'} = $this->toFileID();
        $out->{'fileName'} = $this->toFileName();
        $out->{'fileUrl'} = $this->toFileURL();
        $out->{'notifyUrl'} = $this->toNotifyURL();
        $out->{'transferType'} = $this->toTransferType();
        return $out;
    }

    /**
     * @param stdClass $obj
     * @return ApifoxSchema
     * @throws Exception
     */
    public static function from(stdClass $obj): ApifoxSchema {
        return new ApifoxSchema(
            ApifoxSchema::fromFile($obj->{'file'})
            ,ApifoxSchema::fromFileHash($obj->{'fileHash'})
            ,ApifoxSchema::fromFileID($obj->{'fileId'})
            ,ApifoxSchema::fromFileName($obj->{'fileName'})
            ,ApifoxSchema::fromFileURL($obj->{'fileUrl'})
            ,ApifoxSchema::fromNotifyURL($obj->{'notifyUrl'})
            ,ApifoxSchema::fromTransferType($obj->{'transferType'})
        );
    }

    /**
     * @return ApifoxSchema
     */
    public static function sample(): ApifoxSchema {
        return new ApifoxSchema(
            ApifoxSchema::sampleFile()
            ,ApifoxSchema::sampleFileHash()
            ,ApifoxSchema::sampleFileID()
            ,ApifoxSchema::sampleFileName()
            ,ApifoxSchema::sampleFileURL()
            ,ApifoxSchema::sampleNotifyURL()
            ,ApifoxSchema::sampleTransferType()
        );
    }
}